### ISSUE TITLE
No backspace mode

### ISSUE THREAD

**Issue by davisriedel** [davisriedel/obsidian-typewriter-mode#15]
We could consider adding a "no backspace" mode like in a real typewriter, but this may be out of scope of this plugin.

**Comment by brocodile** [comment]
Hey thats a great idea. The plugin would live upto it's name, maybe add this something like an experimental feature.

**Comment by winged-voices** [comment]
Definitely upvoting this! Something I've been looking for is an app or plugin that would get me out of the habit of over-editing and that would be fantastic to have.

**Comment by davisriedel** [comment]
I just found out, that there is a plugin that implements just this: [jobedom/obsidian-hemingway-mode](https://github.com/jobedom/obsidian-hemingway-mode). I am thus closing this issue for now.
