### ISSUE TITLE
Extra Extra space at top still 

### ISSUE THREAD

**Issue by yarub123** [davisriedel/obsidian-typewriter-mode#27]
Sorry, I know this is your beta release, I followed your link from the original "Typewriter Scroll" when you replied to this issue on there (the issue of the extra space)

But the issue still exists 😞:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/84487964/231338646-a760c0ce-594c-4952-a6c7-ece40d76b078.png">

**Comment by davisriedel** [comment]
Sorry, I believe I misunderstood the original issue. I thought you meant the space between the inline title/file name and the text itself. The extra space at the top is needed to be able to shift down the text while typewriter scrolling. Could you please describe the behavior you’re expecting a bit more? Do you want the extra space removed while not typing/while scrolling (with the mouse) through the text? I could remove it during scrolling but this might lead to a jump of the text. I will try a few approaches.

**Comment by yarub123** [comment]
Apologies, I should've clarified. Also now that you mention it, it makes complete sense why you have the space at the top LOL. For some reason me and 2 or 3 other guys, thought it was maybe a small bug. Sorry for the misunderstanding.

Hmm, yeah I guess without that space at the top it would be odd for someone, especially on a newly created note....

A work-around would be to have an option to enable it ONLY for new notes, and to allow the user to choose a line number....For ex:
- "Keep space only to line number: 30"
- After reaching that space it can then turn off the spacing seen at the top...making a cleaner transition when scrolling to the top and/or to the title...

or alternatively, maybe enabling the plugins function to turn on only AFTER reaching a certain line number.... 
- After reaching line 30, plugin turns on, and the top section of the chart won't be noticeable....

Or just simply giving the user the option to completely disable the spacing at the top...I think I recall a plugin back in the day that had this typewriter effect, but without the space at the top.
- I think you could just maintain focus on the line the user is on, it still gives the typewriter effect imo

These are just some thoughts off the top of my head, they are pretty bad but they may also inspire a new way of approaching it 🤷

If a good idea comes up, I'll make sure to drop by and see your thoughts on it. 

Thanks for the replies, and I wish I could've been more helpful Davis. Take care!

**Comment by davisriedel** [comment]
@yarub123 Thanks a lot for your input and ideas!

In the last commit, I rewrote several parts of the underlying code mirror extension. It now takes the actual position of the caret into account.

Theres now a toggle to only engage the typewriter scrolling once the text has reached the offset. This removes the space at the top. Also the active line highlight is now not disappearing anymore when clicking in the text, but actually moves with the cursor and it can now be enabled independently of typewriter scrolling.

I will close the issue for now. Feel free to check out the implementation and give me feedback (but bear in mind, that there are still some glitches that need to be fixed until the next beta release).

**Comment by yarub123** [comment]
@davisriedel Good man, very much appreciated. 

Wow just tried it. Brilliant touch ups Davis, This is a beautiful surprise. I'm glad you figured a work-around. I think it is absolutely so much better like this. Love it. 

No issues on my end, at least so far 😬

Thank you for the update, apologies for the late reply, I hadn't got on Git for a few days. This update is beautiful and works amazing. 

I have one last small question, I am confused as to this option: 
<img width="764" alt="image" src="https://user-images.githubusercontent.com/84487964/233283979-ed2399dd-286e-4a22-9da9-bbe3c591c522.png">

by default I think it is off, but turning it on and off I am not sure what I should be seeing differently. Or maybe I don't know what focused editor is? 

Thanks again, really love this commit 🙏

**Comment by davisriedel** [comment]
@yarub123 Thanks for your feedback. I'm glad you like it! :D

Regarding the "Only in Focused Editor" features: If you have multiple notes opened at once e.g. side-by-side, it will only show the highlighted line in the note your cursor is currently on. If disabled, all notes/editors will show the current line/last line the cursor was on.

Do you have an idea how one could describe this feature better? I inted on renaming the "highlight typewriter line" features anyway, since (with the last few commits) not only the typewriter line is highlighted but the line the cursor is on.

**Comment by yarub123** [comment]
I would keep the "Only in Focused Editor" but in the small description
under it maybe add "Enabling this feature will only show highlighted line
in active note, the one your cursor is on" or something like that :)

Cheers, thanks for the follow up!
