### ISSUE TITLE
Typewriter dimming does not work on separate window

### ISSUE THREAD

**Issue by ironhak** [davisriedel/obsidian-typewriter-mode#36]
Hello, if I enable "Toggle typewriter scrolling and dimming on current paragraph" the dimming feature does not work if I'm not on the main obsidian window.

**Comment by davisriedel** [comment]
Is "separate window" referring to the window of a different vault? Unfortunately there is no way to exchange information between vaults, because each vault loads a new instance of all plugins. Thus the dimming cannot sync across vault windows.

**Comment by ironhak** [comment]
> Is "separate window" referring to the window of a different vault? Unfortunately there is no way to exchange information between vaults, because each vault loads a new instance of all plugins. Thus the dimming cannot sync across vault windows.

Obsidian has a feature that allow to open a note on a separate window (same vault, different window).

**Comment by davisriedel** [comment]
I released a (possible) fix as version 0.0.3-beta.2 which you can install using the BRAT plugin (as described in the README). Feel free to check it out and tell me if it works for you, so that I can include this in the next release.
