### ISSUE TITLE
Bug when using vim mode in long notes

### ISSUE THREAD

**Issue by Hope2KZ** [davisriedel/obsidian-typewriter-mode#38]
Edit a note of about 5000 lines content, whenever I use "j" or "k" to move, the plugin will behave very stuck, there is no way to use. 
   “typewriter scorll” Although the function of this plugin is simple, it does not cause stalling, I hope it can be optimized.(obsidian version: v1.4.16)

By translation software !

**Comment by davisriedel** [comment]
I just published a fix for issue #39 as version 0.0.3-beta.1. You can install this beta with the BRAT plugin (as described in the README). Does this fix your issue? If not, could you please describe how the plugins behavior differs from the expected behavior?

**Comment by davisriedel** [comment]
I just released the new version 0.0.3 publicly. Thanks for your feedback.
