### ISSUE TITLE
Enhancement request: Quick enable/disable toggle for Typewriter mode

### ISSUE THREAD

**Issue by uyhun** [davisriedel/obsidian-typewriter-mode#49]
Enhancement request: The ability to quickly enable/disable Typewriter mode

Scenario / Use case: I like to have the plugin enabled / certain features on (ex. dim paragraph, typewriter scroll, and highlight line) when I'm writing but I don't like the plugin enabled / those features on when I'm not doing heads down writing. As is, to switch between the two modes I'd either have to click into Obsidian settings and enable / disable the plugin entirely OR toggle on / off the three features I like to have on while the plugin is enabled by clicking in, using the command palette, or using hot keys. Both seem onerous and I default to just turning off the plugin entirely and doing without it. Possible solve could be a parent toggle that I can use when the plugin is enabled to switch between the modes... Maybe I could assign a hotkey or something to this too :)

Thanks for all the work developing this!

**Comment by davisriedel** [comment]
@uyhun Thanks for your request. I added this command alongside a few others to toggle certain features. This is included in the latest release `0.0.6`.

**Comment by uyhun** [comment]
Amazing! Thanks @davisriedel . Share a little kudos your way. 

I think others have logged but there are some small bugs that persist when toggling features and not being applied until a restart. But even this enhancement has been great. Thanks!

**Comment by davisriedel** [comment]
@uyhun Thanks a lot for your support. I also noticed a few bugs left in my everday use, I will try to fix those as soon as possible. Once all major bugs are ironed out, I will release version 1.0.
