### ISSUE TITLE
Typewriter offset not working

### ISSUE THREAD

**Issue by Drakemoor** [davisriedel/obsidian-typewriter-mode#51]
Anything above Typewriter offset > 55 is not working. 

If I put any value bigger than that, it just stops doing anything.

There are no errors in the console.

**Comment by davisriedel** [comment]
I could not reproduce this in my test vault. Do you have any other plugins that interfere with scrolling? Maybe it only occurs when the window has a certain size or the display has a certain resolution. Please provide a few more details.

**Comment by davisriedel** [comment]
I am closing this issue for now. Please reach out, if the issue persists and provide the requested details.
