### ISSUE TITLE
Toggling "Typewriter Mode" does not disable all features.

### ISSUE THREAD

**Issue by adsilcott** [davisriedel/obsidian-typewriter-mode#54]
Specifically, I use the dim other paragraphs feature. When I finish a writing session I use the "Toggle Typewriter Mode Plugin On/Off" command, but while some features turn off, the paragraph dimming feature stays on. 

In fact it seems to exhibit a strange behavior where the dimming will turn off after I scroll the page and it will seem normal, but then I switch to another program and when I switch back the other paragraphs are dim again.

I've experienced this in my main vault as well as in a test vault with all other plugins removed.

**Comment by alxmjo** [comment]
I find that I can sometimes get the paragraph dimming to turn off by using the scroll wheel.

**Comment by alxmjo** [comment]
> I find that I can sometimes get the paragraph dimming to turn off by using the scroll wheel.

Never mind. Looks like the buggy behavior returns when I click on another window and then come back to Obsidian.

**Comment by davisriedel** [comment]
This should be fixed in the latest commit. I will release a new version soon.
