### ISSUE TITLE
Cannot Edit Amount of Lines Above and Below Cursor

### ISSUE THREAD

**Issue by ollyisonit** [davisriedel/obsidian-typewriter-mode#56]
When I enable "Keep lines above and below" in the settings, I'm unable to edit the amount of lines above and below the current line.

![image](https://github.com/davisriedel/obsidian-typewriter-mode/assets/56850051/46dbf094-4cd7-461b-b7ff-9294164a9fe3)

I currently have no features enabled other than "Keep lines above and below".

**Comment by davisriedel** [comment]
Fixed in commit [d6e3fd3](https://github.com/davisriedel/obsidian-typewriter-mode/commit/d6e3fd3f9af879e333767498daa51cc5e605ba74). I will release a new version soon.
