### ISSUE TITLE
TW with Obsidian Tables doesn't work.

### ISSUE THREAD

**Issue by DoTrONoL** [davisriedel/obsidian-typewriter-mode#61]
You can check in the view below.

https://github.com/davisriedel/obsidian-typewriter-mode/assets/71497422/7f8b10da-af2c-45b6-b842-51d03c50044b

**Comment by neilfranci** [comment]
same issues, whenever I reach the table it jumps past the end of the file.

**Comment by Fred-Vatin** [comment]
I wonder if it would be possible for the plugin to disable itself when the caret is in a table only when in source/preview mode. That would be a solution.

**Comment by joredas** [comment]
When typping anything in table at "Live Preview" mode, the cursor jumps to the top.

**Comment by joredas** [comment]
When typing anything in table at "Live Preview" mode, the cursor jumps to the top.

**Comment by davisriedel** [comment]
This is resolved in the latest beta. You can install it with the BRAT plugin. Typewriter Scrolling now disables itself as soon as you enter a table.
