### ISSUE TITLE
[Bug] Toggle dimming unfocused paragraphs doesn't work

### ISSUE THREAD

**Issue by ulahcherubim** [davisriedel/obsidian-typewriter-mode#63]
Using the command or keyboard shortcut to toggle dimming unfocused paragraphs is not working, the setting persists.

**Comment by davisriedel** [comment]
Also fixed with commit [fd4a012](https://github.com/davisriedel/obsidian-typewriter-mode/commit/fd4a012dc38c168f816058c2f167aa63e940fe9f). I will release a new version soon.
