### ISSUE TITLE
Fullscreen focus interferes with vim mode

### ISSUE THREAD

**Issue by purung** [davisriedel/obsidian-typewriter-mode#64]
Hi, thank you for the plugin! I found it to be really useful except for one paper cut: when in focus mode, <Esc> exits fullscreen. When using vim keybindings, you need <Esc> to jump between editing modes. Maybe this is out of your hands, but if the exits focus mode keyboard shortcut could be customizable, that would be grand :)

**Comment by davisriedel** [comment]
I have completely rewritten the fullscreen mode in the latest commit. This should fix this issue as well. If not, please don't hesitate to reopen this issue.
