### ISSUE TITLE
BUG: Typewrite Mode can't handle data tables.

### ISSUE THREAD

**Issue by ianTevesAcc** [davisriedel/obsidian-typewriter-mode#65]
The plugin has a type error when accessing a data table in Obsidian. The Type error happens when you have highlight underline on.

Steps to reproduce:
1. Install Typewriter Mode plugin
2. Turn on "highlight current line"
3. create a data table
4. click a cell of the data table or go up to it. (it may take a couple of mins to reproduce error.)

Expected the line highlighting to turn off.  Instead it produces a type error and cannot select the data table cell.

Additional info:
When highlight is off, the error is not reproduced, but the typewrite centering mode no longer works.

Files:
![image](https://github.com/davisriedel/obsidian-typewriter-mode/assets/105651670/52256839-1f83-480b-9074-9cdd285b05ca)
[obsidian.md-1715418142370.log](https://github.com/davisriedel/obsidian-typewriter-mode/files/15282260/obsidian.md-1715418142370.log)

**Comment by davisriedel** [comment]
Closed in favor of #61
