### ISSUE TITLE
Compatible with another plugin lineage

### ISSUE THREAD

**Issue by calmwaves111** [davisriedel/obsidian-typewriter-mode#67]
I am using another plugin at the same time https://github.com/ycnmhd/obsidian-lineage
When two plugins are turned on simultaneously, once I start typing, the input box will run to the top and I cannot see the text I am typing

I've raised an issue with that plugin https://github.com/ycnmhd/obsidian-lineage/issues/41

maybe  typewriter-mode should ignore editor instances that are within [lineage view](https://github.com/ycnmhd/obsidian-lineage/blob/8e46ab053304b8d977cd2533bc6dc04650bdd388/src/view/view.ts#L32)

**Comment by NewTypo** [comment]
Encountering compatibility issues as well, currently can only use one of them 😢

**Comment by davisriedel** [comment]
Thank you for opening the issue. Since the plugin causes issues with several plugins (e.g. canvas, kanban, lineage) and it is out of scope to make it compatible with all plugins, I decided to only enable it in markdown files from the next version on. Please report if any issues remain.
