### ISSUE TITLE
Feature Request: Disable per File for Multpane view

### ISSUE THREAD

**Issue by CGPGrey** [davisriedel/obsidian-typewriter-mode#68]
Plug in is great, couldn't imagine using obsidian without it. 

I do have a feature for consideration: I'm often working with a central script, surrounded on either side by two or four other panes with information relevant to what I'm working on.   

Typewriter mode is essential for the central script, but very annoying for the side panes, which waste a lot of space at the top.  The current workaround is enabling the option so scroll only starts on interaction, but I am interacting with those side panes a lot, so have to reset them.

It would be great if I could add a tag, or a property to a file to tell typewriter mode to never typewriter scroll on that file.  

Thank you again for making this plug in and improving every hour I spend in the app with all the options.

-Grey

**Comment by davisriedel** [comment]
This is implemented in 1.0.0-beta.8. You can now disable the plugin on a per-file basis. Include `typewriter-mode: false` in the file's frontmatter to disable the plugin in that file. Please let me know if it works for your use-case.

**Comment by CGPGrey** [comment]
Thank you so much for adding this.
