### ISSUE TITLE
Can't easily enable/disable

### ISSUE THREAD

**Issue by alienbogart** [davisriedel/obsidian-typewriter-mode#69]
It doesn't seem to be possible to completely disable this plugin without opening the Obsidian's settings. Even if I disable through the command to toggle Typewriter Mode, the paragraphs are still dimmed. Nice plugin, I will probably use at some point, but that seems needlessly cumbersome. Also, the "on/off" command for the entire mode should have a short and obvious name so it is not buried in a sea of Typewritter Mode commands on the Command Palette.

**Comment by davisriedel** [comment]
This should be fixed with the latest commit. I will release a new version soon.
