### ISSUE TITLE
Current line highlight vertical offset when using a custom line height

### ISSUE THREAD

**Issue by mariano-ruggiero** [davisriedel/obsidian-typewriter-mode#72]
I'm using the following CSS snippet to change the line height in edit mode:

`.cm-contentContainer {
    line-height: 2.0;
}
`

When that's on, the line highlight box seems to render at an offset instead of being properly vertically-aligned with the current line. I would expect it to behave like the normal text selection, as it does when no line height style is applied. (Actually, looking at my screenshots, there's a 1 pixel offset even with no CSS style. I wonder if the bug is present there and just gets magnified with a taller line height 🤔)

**No custom CSS:**
<img width="247" alt="Screenshot 2024-07-04 at 13 45 13" src="https://github.com/davisriedel/obsidian-typewriter-mode/assets/145186705/fcafae6e-07b5-47a4-9d03-e5f7a468a3f9">

**With custom CCS snippet:**
<img width="250" alt="Screenshot 2024-07-04 at 13 45 37" src="https://github.com/davisriedel/obsidian-typewriter-mode/assets/145186705/2056907e-8278-4482-ada3-ec4d84579fda">

This is on Obsidian 1.6.5, running on macOS 14.5.

**Comment by davisriedel** [comment]
This should be fixed in the latest commit. I will release a new version soon.
