### ISSUE TITLE
Jumping to the first line not working ("Only maintain offset when reached" active)

### ISSUE THREAD

**Issue by lebigot** [davisriedel/obsidian-typewriter-mode#73]
When "Only maintain typewriter offset when reached" is active, going from the end of a (long enough) note to the top with a "single" keyboard action (for instance with the gg command in vim mode) has a display bug: the cursor moves to the top of the file, but the top of the file is not at all visible. Instead, a region below the top of the file is displayed (and we don't see the cursor).

The problem persists even if moving the cursor (with the arrow keys): the top of the file gets displayed at each key stroke for a fraction of a second, and then the display moves back to a region below the top of the file, where we don't see the (first) line with the cursor.

Current workaround: disable "Only maintain offset when reached" (which is not ideal).

Configuration:
- Obsidian 1.6.5 (147).
- iOS
- External keyboard
- iPhone 13

**Comment by davisriedel** [comment]
This should be fixed in the latest commit. I will release it in a new version soon.
