### ISSUE TITLE
Weirdness in canvas

### ISSUE THREAD

**Issue by Ario99** [davisriedel/obsidian-typewriter-mode#75]
I like this plugin a lot but I also use canvas sometimes so I disable this plugin whenever I want to edit text in canvas. If this plugin didn't effect how editing in canvas works then that would be a viable hotfix.

**Comment by davisriedel** [comment]
There is an option in settings that lets you disable the plugin in canvas. Have you tried this? If the problem persists, please reach out to me again.

**Comment by davisriedel** [comment]
Edit: Since the plugin causes issues with several plugins (e.g. canvas, kanban, lineage) and it is out of scope to make it compatible with all plugins, I decided to only enable it in markdown files from the next version on. This means that it should now be disabled in canvas by default.

**Comment by Ario99** [comment]
I hadn't tried that, sorry for not checking plugin settings. XD



> Edit: Since the plugin causes issues with several plugins (e.g. canvas, kanban, lineage) and it is out of scope to make it compatible with all plugins, I decided to only enable it in markdown files from the next version on. This means that it should now be disabled in canvas by default.

Yeah this seems like a smart move, thanks for the great work!
