### ISSUE TITLE
Unfocused by "list" 

### ISSUE THREAD

**Issue by luketoys** [davisriedel/obsidian-typewriter-mode#86]
I really love this plugin but I write a lot using nested lists. I have to turn it off in these cases because I can't easily see what I'm connecting this bullet to.

- parent
    - child 1 
    - child 2 
         - grandchild 1
         - grandchild 2 

It'd be nice when typing in a list, it highlights every parent of that bullet. (ex. writing in grandchild 1 would highlight only child 2 and parent). But it would stay centered on the bullet with the deepest nest. I don't have any coding experience, but I do know there's some discussion around "bullet threading" which is a plugin in logseq that does something similar.

**Comment by davisriedel** [comment]
Thanks for your feature request. This is implemented in the latest beta 0.0.15-beta.2. You can download it via BRAT (see the README). Please try it and let me know if you have any problems or further suggestions.
