### ISSUE TITLE
Text width changes when not in typewriter mode

### ISSUE THREAD

**Issue by lebigot** [davisriedel/obsidian-typewriter-mode#91]
This module is my favorite typewriter module, but I refrain to use it because of the following problem.

When the window is relatively narrow (or on an iPhone), we can see that the margins change and become quite large when typewriter mode becomes *deactivated*.

It would be useful that the margins do not change between both modes (and are not too big, like when not using this plugin): otherwise lines are really short and harder to read, on an iPhone.

**Comment by davisriedel** [comment]
This should be fixed in the latest release, `1.0.0-rc.4`. You're welcome to try it. Please reach out to me, if the problem persists.

**Comment by lebigot** [comment]
Perfect, thanks a lot!! I switched back to using this plugin!
