### ISSUE TITLE
Fluent Scroll

### ISSUE THREAD

**Issue by GreyElaina** [davisriedel/obsidian-typewriter-mode#94]
the text could smoothly scrolls in a continuous, uninterrupted manner when typing. currently, center-ing behaves a noticeable effect: the cursor and above text twinkles.

![CleanShot 2024-10-24 at 01 42 32](https://github.com/user-attachments/assets/c87bb508-8287-45fd-bf76-17628cadad88)

I appreciate your consideration of this request. Thank you for your hard work!

**Comment by davisriedel** [comment]
You can achieve this with the following CSS snippet:

`.cm-scroller { scroll-behavior: smooth; }`

However, this alters how Code Mirror scrolls and is thus not perfect. There appears to be no better way to have some kind of smooth scrolling. I am closing this issue for now.
