### ISSUE TITLE
Notes in Maximized New Window, No Typewriter Scrolling

### ISSUE THREAD

**Issue by ChuckWheat** [davisriedel/obsidian-typewriter-mode#98]
Edit: This was 0.0.14, just confirmed same behavior in 1.0.0.

https://github.com/user-attachments/assets/5cf9304f-133d-4c20-9969-4613537e378b

Typewriter scrolling does not work for notes in new windows that are also maximized.

Edit: 1.0.0 fixed> The highlight line does not enable in the new window until toggled.

**Comment by davisriedel** [comment]
If I understand you correctly, this is fixed in 1.0.0? If not, please open an issue.
